import type { Location } from '@/types/location';

// Australian cities
export const southAustralianCities: string[] = [
  "Adelaide",
  "Mount Gambier",
  "Whyalla",
  "Port Lincoln",
  "Victor Harbor",
  "Port Augusta",
  "Murray Bridge",
  "Port Pirie",
  "Gawler",
  "Mount Barker",
  "Nuriootpa",
  "Naracoorte",
  "Kadina",
  "Moonta",
  "Barmera",
  "Berri",
  "Bordertown",
  "Ceduna",
  "Clare",
  "Coober Pedy",
  "Goolwa",
  "Jamestown",
  "Kingston SE",
  "Mannum",
  "Meningie",
  "Millicent",
  "Orroroo",
  "Penola",
  "Port Broughton",
  "Port Elliot",
  "Port MacDonnell",
  "Port Wakefield",
  "Quorn",
  "Renmark",
  "Robe",
  "Roxby Downs",
  "Strathalbyn",
  "Streaky Bay",
  "Tanunda",
  "Waikerie",
  "Wallaroo",
  "Willunga",
  "Woodside",
  "Yankalilla",
  "Yorketown",
  
  // New locations
  "Kootaberra",
  "Koppamurra",
  "Koppio",
  "Korunye",
  "Kringin",
  "Krondorf",
  "Krongart",
  "Kudla",
  "Kuitpo",
  "Kuitpo Colony",
  "Kulpara",
  "Kurralta Park",
  "Kyancutta",
  "Kybunga",
  "Kybybolite",
  "Kyeema",
  "Laffer",
  "Lake Albert",
  "Lake Alexandrina",
  "Lake Carlet",
  "Lake Everard",
  "Lake Eyre",
  "Lake Frome",
  "Lake Gairdner",
  "Lake Gilles",
  "Lake Harris",
  "Lake Macfarlane",
  "Lake Plains",
  "Lake Torrens",
  "Lake Torrens Station",
  "Lake View",
  "Lameroo",
  "Langhorne Creek",
  "Langs Landing",
  "Largs Bay",
  "Largs North",
  "Laura",
  "Laura Bay",
  "Laurie Park",
  "Leabrook",
  "Leasingham",
  "Leawood Gardens",
  "Leigh Creek",
  "Leigh Creek Station",
  "Leighton",
  "Lenswood",
  "Lewiston",
  "Light Pass",
  "Lightsview",
  "Lincoln Gap",
  "Lincoln National Park",
  "Linden Park",
  "Lindley",
  "Lindon",
  "Linwood",
  "Lipson",
  "Little Douglas",
  "Littlehampton",
  "Lobethal",
  "Lochaber",
  "Lochiel",
  "Lock",
  "Lockes Claypan",
  "Lockleys",
  "Long Flat",
  "Long Plains",
  "Longwood",
  "Lonsdale",
  "Lonsdale Dc",
  "Louth Bay",
  "Loveday",
  "Lowan Vale",
  "Lowbank",
  "Lower Broughton",
  "Lower Hermitage",
  "Lower Inman Valley",
  "Lower Light",
  "Lower Mitcham",
  "Loxton",
  "Loxton North",
  "Lucindale",
  "Lucky Bay",
  "Lyndhurst",
  "Lyndoch",
  "Lynton",
  "Lyrup",
  "Maaoupe",
  "Mabel Creek",
  "Macclesfield",
  "Macdonald Park",
  "Macgillivray",
  "Macumba",
  "Magarey",
  "Magdala",
  "Maggea",
  "Magill",
  "Magill North",
  "Magill South",
  "Mahanewo",
  "Maitland",
  "Makin",
  "Malinong",
  "Mallala",
  "Malpas",
  "Maltee",
  "Malvern",
  "Mambray Creek",
  "Mangalo",
  "Manna Hill",
  "Mannanarie",
  "Manners Well",
  "Manningham",
  "Mannum",
  "Manoora",
  "Mansfield Park",
  "Mantung",
  "Manunda Station",
  "Marama",
  "Marananga",
  "Marble Hill",
  "Marcollat",
  "Marden",
  "Marino",
  "Marion",
  "Marion Bay",
  "Markaranka",
  "Marks Landing",
  "Marla",
  "Marleston",
  "Marleston Dc",
  "Marola",
  "Marrabel",
  "Marree",
  "Marree Station",
  "Marryatville",
  "Martins Well",
  "Maryvale",
  "Maslin Beach",
  "Matta Flat",
  "Maude",
  "Mawson Lakes",
  "Mayfield",
  "Maylands",
  "Mcbean Pound",
  "Mccallum",
  "Mccracken",
  "Mcdouall Peak",
  "Mcharg Creek",
  "Mclaren Flat",
  "Mclaren Vale",
  "Meadows",
  "Medindie",
  "Medindie Gardens",
  "Melrose",
  "Melrose Park",
  "Melrose Park Dc",
  "Melton",
  "Melton Station",
  "Meningie",
  "Meningie East",
  "Meningie West",
  "Menzies",
  "Mercunda",
  "Merghiny",
  "Meribah",
  "Merriton",
  "Merty Merty",
  "Middle Beach",
  "Middle River",
  "Middleback Range",
  "Middleton",
  "Midgee",
  "Mil Lel",
  "Milang",
  "Mile End",
  "Mile End South",
  "Milendella",
  "Millbrook",
  "Millers Creek",
  "Millicent",
  "Millswood",
  "Miltalie",
  "Minbrie",
  "Minburra",
  "Minburra Plain",
  "Minburra Station",
  "Mindarie",
  "Mingary",
  "Mingbool",
  "Minlaton",
  "Minnipa",
  "Mintabie",
  "Mintaro",
  "Minvalara",
  "Miranda",
  "Mitcham",
  "Mitcham Shopping Centre",
  "Mitchell",
  "Mitchell Park",
  "Mitchellville"
];

export const victorianCities: string[] = [
  "Melbourne",
  "Geelong",
  "Ballarat",
  "Bendigo",
  "Shepparton",
  "Mildura",
  "Warrnambool",
  "Wodonga",
  "Traralgon",
  "Sale",
  "Wangaratta",
  "Horsham",
  "Bairnsdale",
  "Ararat",
  "Benalla",
  "Colac",
  "Echuca",
  "Hamilton",
  "Moe",
  "Morwell",
  "Ocean Grove",
  "Portland",
  "Swan Hill",
  "Torquay",
  "Warragul",
  "Castlemaine",
  "Cobram",
  "Kyabram",
  "Lakes Entrance",
  "Lara",
  "Maryborough",
  "Pakenham",
  "Phillip Island",
  "Sunbury",
  "Yarrawonga"
];

export const newSouthWalesCities: string[] = [
  "Sydney",
  "Newcastle",
  "Wollongong",
  "Maitland",
  "Coffs Harbour",
  "Wagga Wagga",
  "Port Macquarie",
  "Tamworth",
  "Orange",
  "Dubbo",
  "Bathurst",
  "Albury",
  "Nowra",
  "Lismore",
  "Armidale",
  "Goulburn",
  "Broken Hill",
  "Cessnock",
  "Grafton",
  "Griffith",
  "Taree",
  "Forster",
  "Queanbeyan",
  "Kiama",
  "Batemans Bay",
  "Byron Bay",
  "Lithgow",
  "Moree",
  "Mudgee",
  "Muswellbrook",
  "Parkes",
  "Singleton",
  "Ulladulla",
  "Yass",
  "Young"
];

export const queenslandCities: string[] = [
  "Brisbane",
  "Gold Coast",
  "Sunshine Coast",
  "Townsville",
  "Cairns",
  "Toowoomba",
  "Mackay",
  "Rockhampton",
  "Bundaberg",
  "Hervey Bay",
  "Gladstone",
  "Mount Isa",
  "Maryborough",
  "Gympie",
  "Emerald",
  "Innisfail",
  "Kingaroy",
  "Airlie Beach",
  "Atherton",
  "Ayr",
  "Biloela",
  "Bowen",
  "Charters Towers",
  "Chinchilla",
  "Dalby",
  "Goondiwindi",
  "Ingham",
  "Longreach",
  "Port Douglas",
  "Roma",
  "Stanthorpe",
  "Warwick",
  "Yeppoon"
];

export const westernAustralianCities: string[] = [
  "Perth",
  "Bunbury",
  "Geraldton",
  "Kalgoorlie",
  "Albany",
  "Broome",
  "Busselton",
  "Esperance",
  "Karratha",
  "Port Hedland",
  "Carnarvon",
  "Collie",
  "Derby",
  "Dunsborough",
  "Exmouth",
  "Kununurra",
  "Manjimup",
  "Margaret River",
  "Merredin",
  "Narrogin",
  "Newman",
  "Northam",
  "Tom Price"
];

export const tasmanianCities: string[] = [
  "Hobart",
  "Launceston",
  "Devonport",
  "Burnie",
  "Ulverstone",
  "Kingston",
  "Wynyard",
  "New Norfolk",
  "Bridgewater",
  "Sorell",
  "Deloraine",
  "George Town",
  "Huonville",
  "Longford",
  "Perth",
  "Queenstown",
  "Scottsdale",
  "Sheffield",
  "Smithton",
  "St Helens",
  "Swansea",
  "Westbury",
  "Zeehan"
];

export const northernTerritoryCities: string[] = [
  "Darwin",
  "Alice Springs",
  "Katherine",
  "Tennant Creek",
  "Nhulunbuy",
  "Jabiru",
  "Yulara",
  "Alyangula",
  "Borroloola",
  "Elliott",
  "Pine Creek",
  "Timber Creek"
];

export const actCities: string[] = [
  "Canberra",
  "Belconnen",
  "Gungahlin",
  "Tuggeranong",
  "Woden Valley",
  "Weston Creek",
  "Queanbeyan"
];

// Helper function to convert a string city name to a Location object
const createLocationFromString = (cityName: string): Location => {
  const slug = cityName.toLowerCase().replace(/[\s(),'&-]+/g, '-').replace(/--+/g, '-');
  return {
    id: slug,
    name: cityName,
    slug: slug,
    state: "Various",
    country: "Australia",
    image: "/placeholder.svg"
  };
};

// Convert all string cities to Location objects
const convertCitiesToLocations = (cities: string[]): Location[] => {
  return cities.map(city => createLocationFromString(city));
};

// Convert all city arrays to Location objects
const southAustralianLocations = convertCitiesToLocations(southAustralianCities);
const victorianLocations = convertCitiesToLocations(victorianCities);
const newSouthWalesLocations = convertCitiesToLocations(newSouthWalesCities);
const queenslandLocations = convertCitiesToLocations(queenslandCities);
const westernAustralianLocations = convertCitiesToLocations(westernAustralianCities);
const tasmanianLocations = convertCitiesToLocations(tasmanianCities);
const northernTerritoryLocations = convertCitiesToLocations(northernTerritoryCities);
const actLocations = convertCitiesToLocations(actCities);

// Predefined locations with more details
export const predefinedLocations: Location[] = [
  {
    id: "adelaide",
    name: "Adelaide",
    slug: "adelaide",
    state: "South Australia",
    country: "Australia",
    image: "/images/locations/adelaide.jpg",
    description: "Adelaide is the capital city of South Australia and the fifth-largest city in Australia."
  },
  {
    id: "melbourne",
    name: "Melbourne",
    slug: "melbourne",
    state: "Victoria",
    country: "Australia",
    image: "/images/locations/melbourne.jpg",
    description: "Melbourne is the capital and most-populous city of the Australian state of Victoria."
  },
  {
    id: "sydney",
    name: "Sydney",
    slug: "sydney",
    state: "New South Wales",
    country: "Australia",
    image: "/images/locations/sydney.jpg",
    description: "Sydney is the capital city of the state of New South Wales, and the most populous city in Australia."
  },
  {
    id: "brisbane",
    name: "Brisbane",
    slug: "brisbane",
    state: "Queensland",
    country: "Australia",
    image: "/images/locations/brisbane.jpg",
    description: "Brisbane is the capital and most populous city of Queensland, and the third most populous city in Australia."
  },
  {
    id: "perth",
    name: "Perth",
    slug: "perth",
    state: "Western Australia",
    country: "Australia",
    image: "/images/locations/perth.jpg",
    description: "Perth is the capital and largest city of the Australian state of Western Australia."
  },
  {
    id: "hobart",
    name: "Hobart",
    slug: "hobart",
    state: "Tasmania",
    country: "Australia",
    image: "/images/locations/hobart.jpg",
    description: "Hobart is the capital and most populous city of the Australian island state of Tasmania."
  },
  {
    id: "darwin",
    name: "Darwin",
    slug: "darwin",
    state: "Northern Territory",
    country: "Australia",
    image: "/images/locations/darwin.jpg",
    description: "Darwin is the capital city of the Northern Territory of Australia."
  },
  {
    id: "canberra",
    name: "Canberra",
    slug: "canberra",
    state: "Australian Capital Territory",
    country: "Australia",
    image: "/images/locations/canberra.jpg",
    description: "Canberra is the capital city of Australia and the largest inland city in the country."
  }
];

// Combine all location arrays - now all entries are Location objects
export const allAustralianCities: Location[] = [
  ...predefinedLocations,
  ...southAustralianLocations,
  ...victorianLocations,
  ...newSouthWalesLocations,
  ...queenslandLocations,
  ...westernAustralianLocations,
  ...tasmanianLocations,
  ...northernTerritoryLocations,
  ...actLocations
];

// For backward compatibility, keep allLocations but we don't use it much
export const allLocations: Location[] = allAustralianCities;
